### ISSUE TITLE
loraHandler issue

### ISSUE THREAD

**Issue by mistakeNot7** [beegee-tokyo/RAK4631-LPWAN-Tracker#1]
Hi, I have a strange behavior. All compiles nice and well, the initialization of the boards goes well, but once it hits "Start network join request" (lmh_join()) it doesn't go past that point. On the server side I can see the request and answer both, so I am a bit lost at how to go ahead. Any ideas? I'm using PlatformIO on win 10.

**Comment by beegee-tokyo** [comment]
@mistakeNot7 
Which region are you using? 
If you see join request and join accept packets everything should be ok.

In the log output, do you see `OTAA joined` or just nothing anymore?

Can you add in platformio.ini the LIB_DEBUG build flag:
```ini
build_flags = 
	-DLIB_DEBUG=1
```
This should give more information what happens inside the LoRaWAN library.

**Comment by mistakeNot7** [comment]
> @mistakeNot7
> Which region are you using?
> If you see join request and join accept packets everything should be ok.
> 
> In the log output, do you see `OTAA joined` or just nothing anymore?
> 
> Can you add in platformio.ini the LIB_DEBUG build flag:
> 
> ```ini
> build_flags = 
> 	-DLIB_DEBUG=1
> ```
> 
> This should give more information what happens inside the LoRaWAN library.

I use EU868 region.
OTAA join I cannot see, but then I'm not sure which log you are talking about. I had Serial to give me some debug messages.
I'll add the debug directive and report back. 
thank you for help

**Comment by mistakeNot7** [comment]
I made some small progress, but still getting stuck on lmh_join. At least I've managed to pinpoint where it stops.
![lhm_join](https://user-images.githubusercontent.com/84438871/120474756-42117480-c3b1-11eb-92f8-9bd3da4fb928.JPG)
LoRaMacHelpper.cpp uses LoRaMacMlmeRequest function and there it seems to stop.

**Comment by beegee-tokyo** [comment]
I downloaded the code as is from here and compiled it and it works.
Output on USB Serial:
```log
=====================================
RAK4631 LoRaWan tracker
=====================================
Z low
Y low
X low
=====================================
SX126x initialization
=====================================
Start network join request
OTAA joined and got dev address 014C924B
switch to class C done
Got semaphore
Z low
Y low
X low
More than 10 seconds since last position message, send now
GPS poll finished 
No valid location found
No valid GPS position
UP Lat 0.0000 Lon 0.0000 Alt 0 Pr 0 B 0%
```
Looking on your log, you did not add `-DLIB_DEBUG=1` in platformio.ini. Because the log output would look different, like this:
```log
=====================================
RAK4631 LoRaWan tracker
=====================================
Z low
Y low
X low
=====================================
SX126x initialization
=====================================
<BRD> SyncWord = 2414
<BRD> LoRa Task started
<LMH> OTAA 
DevEui=00-0D-75-E6-56-4D-C1-F5
DevAdd=26021FB5
AppEui=70-B3-D5-7E-D0-02-01-E1
AppKey=2B-84-E0-B0-9B-68-E5-CB-42-17-6F-E7-53-DC-EE-79
<LMH> Selected subband 1
<AS923> Switch to Version 3
<AS923> CH0 - TX 916.6
<AS923> CH1 - TX 916.8
<AS923> CH2 - TX 917.0
<AS923> CH3 - TX 917.2
<AS923> CH4 - TX 917.4
<AS923> CH5 - TX 917.6
<AS923> CH6 - TX 917.8
<AS923> CH7 - TX 918.0
<AS923> RX2 916.6
<LMH> Using AS923-3
<LMH> Selected subband 1
Start network join request
<LM> OnRadioTxDone
<LM> OnRadioTxDone => RX Windows #1 5002 #2 6002
<LM> OnRadioTxDone => TX was Join Request
<LM> OnRadioRxDone
<LM> OnRadioRxDone => FRAME_TYPE_JOIN_ACCEPT
<AS923> Apply CF list: new channel at Freq = 917000000
<AS923> Apply CF list: new channel at Freq = 917200000
<AS923> Apply CF list: new channel at Freq = 917400000
<AS923> Apply CF list: new channel at Freq = 917600000
<AS923> Apply CF list: new channel at Freq = 917800000
<LM> LoRaMacState = idle
OTAA joined and got dev address 0169DF8A
switch to class C done
```
Please try to get the detailed log.

**Comment by mistakeNot7** [comment]
=====================================
RAK4631 LoRaWan tracker
=====================================
Init BLE
Init Batt
Init GPS
Init LoRaWan
=====================================
SX126x initialization
=====================================
<BRD> SyncWord = 2414
<BRD> LoRa Task started
<LMH> OTAA
DevEui=AC-1F-09-FF-FE-03-EF-10
DevAdd=26021FB5
AppEui=B8-27-EB-FF-FE-B6-5C-55
AppKey=7B-CC-60-EA-70-D9-E3-DA-FB-39-A3-52-8C-5C-5F-7A
<LMH> Selected subband 1
<LMH> Selected subband 1
Start network join request

**Comment by mistakeNot7** [comment]
this is all I get with the detailed log activated. You were right I did activate the directive on the wrong project before.
still I don't understand what goes wrong... having the gps indoor didn't seem to cause troubles in your example.

**Comment by beegee-tokyo** [comment]
On EU868 remove these lines from the code:
```c++
        	// For some regions we might need to define the sub band the gateway is listening to
        	// This must be called AFTER lmh_init()
        	/// \todo This is for Dragino LPS8 gateway. How about other gateways???
        	if (!lmh_setSubBandChannels(1))
        	{
        		return 3;
        		Serial.println("lmh_setSubBandChannels failed. Wrong sub band requested?");
        	}
```

Normally this should be ignored on EU868, but just to be sure.
I cannot test on EU868, I have only a gateway for AS923 and it is not simple to switch it to regions outside the 9xxMHz bands.

**Comment by mistakeNot7** [comment]
I've tried this, no joy. But is strange, your Arduino example for tracker works well, but on PlatformIO, almost the same code gives this error. So most likely it is Win10 quirk somewhere (compiler, libraries, etc). Thank you for the time you took.
While not perfect, the Arduino solution works for now ;)
If you don't mind I might bother you in the future regarding Rak4631.

**Comment by beegee-tokyo** [comment]
@mistakeNot7 
Yes, it is really strange, not only that it works when compiled on Arduino IDE but as well that it works for me on AS923-3 (and US915).

Maybe time to get a EU868 gateway, just for testing. It is just difficult, because 868MHz is not a free frequency here.

For any more questions, leave a question here or on the [WisBlock RAK4631 forum](https://forum.rakwireless.com/c/wisblock/67)

**Comment by mistakeNot7** [comment]
Hi beegee, while I make it work on the uplink, from the end device to the gateway, I cannot make it work in downlink. I mean I put the end device in C class mode, chirpstack reports confirmed downlink message, but using lorawan_rx_handler function prints only 0 values for all fields... For sure I do something wrong, but I cannot figure out what exactly.
to give you bit more context, I'm trying to use a Wisgate D0 as sending device and a Rak4631+Rak1910 as end-device, to build a simple drivetest system to measure the Signal Strength. I've started with the GPS_tracker example, but I would like to make the data acquisition on the end-device.

**Comment by beegee-tokyo** [comment]
Can you send me a log of the output you get from the RAK4631? I do not know the WisGate D0, (I have only the Edge gateway). How do you send the data? On which fport?

**Comment by mistakeNot7** [comment]
sorry for delay, crazy days. from chirpstack I've sent messages on fport2. attached are the Rak4631 log from serial, chirpstack message log and the massacred source for arduino. there is a 2h differece between server and node, so the message in chirpstack is at 20210609T21:52:40. the corresponding time for node should be 19:53:40.
if you have the time to point in the right direction would be really nice.
[downlink_issues.zip](https://github.com/beegee-tokyo/RAK4631-LPWAN-Tracker/files/6626294/downlink_issues.zip)
